version: '3.4'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - app-network

  ndfcapismongodb:
    image: ${DOCKER_REGISTRY-}ndfcapismongodb
    build:
      context: .
      dockerfile: NdfcAPIsMongoDB/Dockerfile
    ports:
      - "5107:5107"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDBConnection=mongodb://mongo:27018
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

